# Generated by Django 4.2.7 on 2023-11-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Rent/Mortgage', 'Rent/Mortgage'), ('Transportation', 'Transportation'), ('Food', 'Food'), ('Healthcare', 'Healthcare'), ('Debt Repayment', 'Debt Repayment'), ('Savings', 'Savings'), ('Personal Care', 'Personal Care'), ('Entertainment', 'Entertainment'), ('Clothing', 'Clothing'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Childcare/Children Expenses', 'Childcare/Children Expenses'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=50),
        ),
    ]
