# Generated by Django 4.2.7 on 2023-11-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('Rent/Mortgage', 'Rent/Mortgage'), ('Transportation', 'Transportation'), ('Food', 'Food'), ('Healthcare', 'Healthcare'), ('Debt Repayment', 'Debt Repayment'), ('Savings', 'Savings'), ('Personal Care', 'Personal Care'), ('Entertainment', 'Entertainment'), ('Clothing', 'Clothing'), ('Utilities', 'Utilities'), ('Insurance', 'Insurance'), ('Childcare/Children Expenses', 'Childcare/Children Expenses'), ('Miscellaneous', 'Miscellaneous')], max_length=50, null=True),
        ),
    ]
