# Generated by Django 4.2.7 on 2023-12-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_alter_account_balance_alter_transaction_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
